OOP課題2
kmhm212/oop_2 pull request #1
Opened 2021-04-14 21:46 UTC by kmhm212

2021-04-14 21:47 UTC, kmhm212 commented
strval (文字列への変換)がどこで登場するのかわからず、動作だけ同じになりました。
使うとこ探します。

2021-04-14 22:07 UTC, kazu-taka requested changes
@kmhm212 
`strval`関数は、数値がセットされている変数の文字としての値を取得します！
数値がセットされていて、且つ文字列と結合している部分で使うようにしてみて下さい✨

2021-04-14 22:07 UTC, kazu-taka commented on Taxi.class.php
> +            echo $passenger . "人は降車できません\n";
@kmhm212 
メソッド内でechoしていますが、main.phpでechoしているので、メソッド内ではechoしないようにして下さい🙏

2021-04-14 22:07 UTC, kazu-taka commented on Taxi.class.php
> +
@kmhm212 
細かいですが、ここの空行は削除お願いします:bow:

2021-04-14 22:13 UTC, kazu-taka requested changes
@kmhm212 
コメント1点漏れてました^^;

2021-04-14 22:13 UTC, kazu-taka commented on Taxi.class.php
> +        $this->passenger = $passenger;
@kmhm212 
今の状態で実行すると、`->pickUp(1)`を3回実行してもつねに乗車人数が1になってしますので修正お願いします:bow:

2021-04-15 14:11 UTC, kazu-taka commented
@kmhm212 
数値と文字列を結合してるところを見つけてみて下さい✨

2021-04-18 23:53 UTC, kazu-taka requested changes
@kmhm212 
コメントしたので確認お願いします✨

2021-04-18 23:53 UTC, kazu-taka commented on Taxi.class.php
> +            return strval($passenger) . "人は降車できません\n";
@kmhm212 
ここの`strval`の使い方はOKです👍

2021-04-18 23:53 UTC, kazu-taka commented on Taxi.class.php
> +            '乗車人数:' . strval($this->passenger) . "人\n";
@kmhm212 
車体番号以外は文字列をセットしているので、車体番号以外のstrvalは削除してOKです✨

2021-04-21 13:03 UTC, kmhm212 commented
strvalにいて。ここで例えば車の車種が「999」やら「TRUE」とかだったらどうなんだろう、と思ったのですが、そもそもインスタンス生成時に文字列として設定してるからその場合は問題ない、という認識であってますか？ であれば、車の車体番号については計算したりしないから、そもそも車体番号についても文字列で設定したらどうなんだろうと思いましたが、いかがでしょうか。

2021-04-21 13:10 UTC, kazu-taka commented
@kmhm212 
> strvalにいて。ここで例えば車の車種が「999」やら「TRUE」とかだったらどうなんだろう、と思ったのですが、そもそもインスタンス生成時に文字列として設定してるからその場合は問題ない、という認識であってますか？ であれば、車の車体番号については計算したりしないから、そもそも車体番号についても文字列で設定したらどうなんだろうと思いましたが、いかがでしょうか。

そうですね！
今回に関して言えば、インスタンスを生成する部分はこちらで決めているので、車体番号のみでOKです！
他でアプリを作る場合は、数字が入ってくる部分については、付けた方が良いと思います✨
むやみやたらにつけると、ここは数値が入ってくるのか？と他の人が思ってしまうので要注意です✨
文字列に対して`strval`を使用してもエラーにならないので、そこは大丈夫だと思います！
確かに車体番号も文字列でもいいかもしれないですね！
もう少し仕様をつめてみます:bow:

![LGTM](https://image.lgtmoon.dev/124427)

2021-04-24 10:18 UTC, merged